### ISSUE TITLE
Question:  Does this support having vcpkg as a project submodule?

### ISSUE THREAD

**Issue by cmannett85** [friendlyanon/setup-vcpkg#1]
The documentation I've seen implies that it checks out vcpkg at a specified commit, but in my case (and a common pattern for projects that use vcpkg) vcpkg is a submodule and therefore already available.

Is there a way of telling `setup-vcpkg` to use the existing vcpkg checkout?  Or if the `path` is set to an existing path will it not checkout vcpkg?

**Comment by friendlyanon** [comment]
Closed with https://github.com/friendlyanon/setup-vcpkg/commit/45028c9c71b358f7ab5421612c996245a80d9294
