### ISSUE TITLE
Windows issue

### ISSUE THREAD

**Issue by aloneguid** [friendlyanon/setup-vcpkg#2]
Thank you, works perfectly on linux and mac, however windows build fails, wonder if you can help?

<img width="651" alt="image" src="https://user-images.githubusercontent.com/3155189/148760557-b09b2bef-9425-404c-bb0e-beef5ca2d9df.png">

**Comment by friendlyanon** [comment]
In PowerShell, you acces env variables with `$env:...`. [Docs](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_environment_variables?view=powershell-7.2).

**Comment by aloneguid** [comment]
thanks, replaced with `${{ env.VCPKG_ROOT }}` which works everywhere like magic. Keep up the good work!
