### ISSUE TITLE
Issue with Windows builds

### ISSUE THREAD

**Issue by int-72h** [friendlyanon/setup-vcpkg#5]
![toast](https://user-images.githubusercontent.com/51890027/205113434-d61b8a55-c4e6-4abf-bff8-e73b674499fa.png)
I've ran into the issue in #2, however even after fixing that I'm still running into an issue.

**Comment by friendlyanon** [comment]
I don't see a `committish` being provided and there is no `vcpkg` submodule in your repo either (https://github.com/ToastWare/oftoast2-gdnative/tree/ci-windows).

I guess the better question here is how did the action succeed?

**Comment by int-72h** [comment]
I think it succeeded due to [this line](https://github.com/friendlyanon/setup-vcpkg/blob/85a802286791d6ef61b4be4b806a4fcac728a894/action.yaml#L18) being optional instead of required.
I'll add a committish now.

**Comment by int-72h** [comment]
OK, added the commitish and now it just recurses untill it hits the recursion depth(?)
I assume I've probably misconfigured something:
![toast](https://user-images.githubusercontent.com/51890027/205131767-e2f8cd9e-37f6-441a-b666-1bca8098091d.png)

**Comment by friendlyanon** [comment]
I took a look at the project's CML file and it's committing almost all sins that should not be committed in CMake. Its contents should be like so:

```cmake
cmake_minimum_required(VERSION 3.18)

project(gddl C)

add_library(gddl src/gddl.c)

target_include_directories(gddl PRIVATE src)

find_path(GODOT_HEADERS_INCLUDE_DIR gdnative_api_struct.gen.h REQUIRED)
target_include_directories(gddl SYSTEM PRIVATE "${GODOT_HEADERS_INCLUDE_DIR}")

find_package(CURL REQUIRED)
find_package(zip REQUIRED)
target_link_libraries(gddl PRIVATE CURL::libcurl zip::zip)
```

Build and install the zip library somewhere before this and provide its install prefix via `CMAKE_PREFIX_PATH`. Set the `GODOT_HEADERS_INCLUDE_DIR` cache variable to the location where the godot headers are checked out. Then your build step in CI should be:

```yaml
- shell: bash
  run: |
    cmake -S zip -B zip/build -DBUILD_SHARED_LIBS=0
    cmake --build zip/build --config Release
    cmake --install zip/build --config Release --prefix zip-prefix

    cmake -B build -DBUILD_SHARED_LIBS=1 "-DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake" -DCMAKE_PREFIX_PATH=zip-prefix -DGODOT_HEADERS_INCLUDE_DIR=godot-headers
    cmake --build zip/build --config Release
```

But it looks like you aren't even using vcpkg, since there is no vcpkg.json file in the repo.

**Comment by int-72h** [comment]
I thought I could just use vcpkg to get the curl library quickly; it appears I was mistaken. Closing.
